# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{freelancer-rails}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Trond Arve Nordheim"]
  s.date = %q{2010-08-21}
  s.description = %q{Ruby on Rails support for the Freelancer.com Ruby gem}
  s.email = %q{tanordheim@gmail.com}
  s.extra_rdoc_files = [
    "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "VERSION"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/freelancer/rails/authorizations_controller.rb",
     "app/views/freelancer/rails/authorizations/new.html.erb",
     "lib/freelancer-rails.rb",
     "lib/freelancer-rails/configuration.rb",
     "lib/freelancer-rails/controllers/helpers.rb",
     "lib/freelancer-rails/routes.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/tanordheim/freelancer-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Freelancer.com API for Ruby on Rails}
  s.test_files = [
    "test/helper.rb",
     "test/test_freelancer-rails.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<freelancer>, ["= 0.1.1"])
    else
      s.add_dependency(%q<freelancer>, ["= 0.1.1"])
    end
  else
    s.add_dependency(%q<freelancer>, ["= 0.1.1"])
  end
end

